apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-server
spec:
  serviceName: discovery-server
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: farmanahmed888/discovery-server:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  clusterIP: None
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-nodeport
  labels:
    app: discovery-server
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761