apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      containers:
        - name: loadbalancer
          image: farmanahmed888/loadbalancer:latest
          ports:
            - containerPort: 8000
          env:
            - name: DISCOVERY_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server.default.svc.cluster.local:8761/eureka"
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: loadbalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
