apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: candidate-frontend
  name: candidate-frontend
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 80
  type: NodePort
  selector:
    io.kompose.service: candidate-frontend
