apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: candidate-service
  name: candidate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: candidate-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: candidate-service
    spec:
      containers:
        - env:
            - name: DISCOVERY_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka
            - name: SPRING_DATASOURCE_PASSWORD
              value: Farman@@5
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://spe-project-db:3306/speproject?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: farmanahmed888/candidate-service:latest
          name: candidate-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
