apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: candidate-service
  name: candidate-service
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  type: NodePort
  selector:
    io.kompose.service: candidate-service
