apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: codeeditor-service
  name: codeeditor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: codeeditor-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: codeeditor-service
    spec:
      containers:
        - image: farmanahmed888/codeeditor-service:latest
          name: codeeditor-service
          ports:
            - containerPort: 9001
              protocol: TCP
      restartPolicy: Always
