apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: codeeditor-service
  name: codeeditor-service
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
  type: NodePort
  selector:
    io.kompose.service: codeeditor-service
