apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: discovery-server
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: discovery-server
    spec:
      containers:
        - image: farmanahmed888/discovery-server:latest
          name: discovery-server
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
