apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: http.port
              value: "9200"
            - name: network.host
              value: 0.0.0.0
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: esdata
            - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              name: elasticsearch-cm1
              subPath: elasticsearch.yml
            - mountPath: /var/log/elasticsearch
              name: elasticsearch-cm2
      restartPolicy: Always
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: esdata
        - configMap:
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
            name: elasticsearch-cm1
          name: elasticsearch-cm1
        - configMap:
            name: elasticsearch-cm2
          name: elasticsearch-cm2
