apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: interviewer-frontend
  name: interviewer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: interviewer-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: interviewer-frontend
    spec:
      containers:
        - image: farmanahmed888/interviewer-frontend:latest
          name: interviewer-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
