apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: load-balancer
  name: load-balancer
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  type: NodePort
  selector:
    io.kompose.service: load-balancer
