apiVersion: v1
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5001
        codec => json
      }
    }


    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
        # index => "%{[fields][application]}-%{[fields][service]}-%{+YYYY.MM.dd}"
        # This will create index names like "userservice-complaintservice-2024.05.20"

        index => "springboot-logs"
      }
      stdout {
        codec => rubydebug
      }
    }
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: logstash
  name: logstash-cm1
