apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - env:
            - name: LS_JAVA_OPTS
              value: -Xmx512m -Xms512m
          image: docker.elastic.co/logstash/logstash:7.10.2
          name: logstash
          ports:
            - containerPort: 5001
              protocol: TCP
            - containerPort: 5001
              protocol: UDP
            - containerPort: 9600
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/logstash/config/logstash.yml
              name: logstash-cm0
              readOnly: true
              subPath: logstash.yml
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: logstash.yml
                path: logstash.yml
            name: logstash-cm0
          name: logstash-cm0
        - configMap:
            name: logstash-cm1
          name: logstash-cm1
