apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: 5001-udp
      port: 5001
      protocol: UDP
      targetPort: 5001
    - name: "9600"
      port: 9600
      targetPort: 9600
  type: NodePort
  selector:
    io.kompose.service: logstash
