apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.10.2
          ports:
            - containerPort: 5001
              protocol: TCP
            - containerPort: 5001
              protocol: UDP
            - containerPort: 9600
              protocol: TCP
          env:
            - name: LS_JAVA_OPTS
              value: "-Xmx512m -Xms512m"
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: logstash-config
          hostPath:
            path: /path/to/your/logstash/config/logstash.yml
            type: File
        - name: logstash-pipeline
          hostPath:
            path: /path/to/your/logstash/pipeline
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
    - name: tcp-5001
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: udp-5001
      protocol: UDP
      port: 5001
      targetPort: 5001
    - name: tcp-9600
      protocol: TCP
      port: 9600
      targetPort: 9600
  type: ClusterIP
