apiVersion: v1
kind: PersistentVolume
metadata:
  name: spe-project-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/spe-project-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spe-project-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
